"""
TokenVault — Auth0 Management API + GitHub Actions
Retrieves per-user GitHub OAuth tokens stored inside Auth0 identities.
Uses those tokens to open GitHub Issues automatically on failure detection.

Auth0 stores the GitHub token when a user logs in via GitHub social connection.
We retrieve it via the Management API (machine-to-machine) at runtime.
"""

import os
import httpx
import logging
from dotenv import load_dotenv

load_dotenv()
log = logging.getLogger("remediation-agent")

SEVERITY_LABELS = {
    "critical": "priority: critical",
    "high":     "priority: high",
    "medium":   "priority: medium",
    "low":      "priority: low",
}

CATEGORY_LABELS = {
    "port_conflict":      "type: port-conflict",
    "disk_full":          "type: disk-full",
    "permission_denied":  "type: permission-denied",
    "oom_kill":           "type: oom-kill",
    "service_crash":      "type: service-crash",
    "connection_refused": "type: connection-refused",
    "ssl_error":          "type: ssl-error",
    "timeout":            "type: timeout",
    "generic_error":      "type: generic-error",
}


class TokenVault:
    def __init__(self):
        self.domain         = os.getenv("AUTH0_DOMAIN")
        self.client_id      = os.getenv("MGMT_CLIENT_ID")
        self.client_secret  = os.getenv("MGMT_CLIENT_SECRET")
        self.audience       = f"https://{self.domain}/api/v2/"

    # ── Auth0 Management API ──────────────────────────────────────────────────

    async def get_mgmt_token(self) -> str | None:
        """Gets a short-lived Management API token via client credentials."""
        url = f"https://{self.domain}/oauth/token"   # fixed: was https// (missing colon)
        payload = {
            "client_id":     self.client_id,
            "client_secret": self.client_secret,
            "audience":      self.audience,
            "grant_type":    "client_credentials",
        }
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                response = await client.post(url, json=payload)
                response.raise_for_status()
                token = response.json().get("access_token")
                log.info("Auth0 mgmt token acquired")
                return token
        except Exception as e:
            log.error(f"Failed to get Auth0 mgmt token: {e}")
            return None

    async def get_github_token(self, user_id: str) -> str | None:
        """
        Retrieves the GitHub OAuth token for a user from Auth0 identities.
        Auth0 stores this automatically when the user logs in via GitHub.
        user_id is the Auth0 'sub' claim, e.g. 'github|12345678'
        """
        mgmt_token = await self.get_mgmt_token()
        if not mgmt_token:
            return None

        url = f"{self.audience}users/{user_id}"
        headers = {"Authorization": f"Bearer {mgmt_token}"}

        try:
            async with httpx.AsyncClient(timeout=10) as client:
                response = await client.get(url, headers=headers)
                response.raise_for_status()
                user_data  = response.json()
                identities = user_data.get("identities", [])
                for identity in identities:
                    if identity.get("provider") == "github":
                        token = identity.get("access_token")
                        log.info(f"GitHub token retrieved for user {user_id[:20]}...")
                        return token
            log.warning(f"No GitHub identity found for user {user_id}")
            return None
        except Exception as e:
            log.error(f"Failed to get GitHub token: {e}")
            return None

    # ── GitHub Issue Creator ──────────────────────────────────────────────────

    async def create_incident_issue(
        self,
        github_token: str,
        repo: str,              # format: "owner/repo-name"
        remediation: dict,
        failure: dict,
        service_name: str,
        environment: str,
        request_id: str,
        actor_name: str,
        permission_level: str,
    ) -> dict | None:
        """
        Opens a GitHub Issue with full incident context.
        Returns the created issue dict or None on failure.
        """
        title = f"[SAIR] {remediation.get('issue', 'System failure detected')}"

        # Build the issue body in GitHub Markdown
        severity   = remediation.get("severity", "unknown")
        confidence = remediation.get("confidence", 0)
        command    = remediation.get("command")

        body = f"""## 🚨 Incident Report — Auto-generated by SAIR

| Field | Value |
|---|---|
| **Request ID** | `{request_id}` |
| **Service** | `{service_name}` |
| **Environment** | `{environment}` |
| **Severity** | `{severity.upper()}` |
| **Failure Category** | `{failure.get('category', 'unknown')}` |
| **Detected By** | `{actor_name}` |
| **Permission Level** | `{permission_level}` |
| **AI Confidence** | `{confidence}%` |
| **Est. Downtime** | `{remediation.get('estimated_downtime', 'unknown')}` |

---

## 🔍 Root Cause

{remediation.get('root_cause', 'Not determined')}

## 🧠 Agent Reasoning

{remediation.get('reasoning', 'N/A')}

## 🛠 Suggested Fix

```
{remediation.get('suggested_fix', 'N/A')}
```
"""

        if command:
            body += f"""
## ⚡ Executable Command (Admin Authorized)

```bash
{command}
```
"""
        else:
            body += """
## 🔒 Executable Command

Not included — requires admin role to unlock.
"""

        body += f"""
## ⏪ Rollback Procedure

```
{remediation.get('rollback', 'N/A')}
```

---
*Auto-generated by [SAIR](https://github.com) · Powered by Vertex AI (Gemini 2.5 Flash) + Auth0*
"""

        # Build labels — ensure they exist or GitHub will silently drop unknown ones
        labels = ["incident", "auto-generated"]
        if sev_label := SEVERITY_LABELS.get(severity):
            labels.append(sev_label)
        if cat_label := CATEGORY_LABELS.get(failure.get("category", "")):
            labels.append(cat_label)

        payload = {
            "title":  title,
            "body":   body,
            "labels": labels,
        }

        url = f"https://api.github.com/repos/{repo}/issues"
        headers = {
            "Authorization": f"token {github_token}",
            "Accept":        "application/vnd.github.v3+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

        try:
            async with httpx.AsyncClient(timeout=15) as client:
                response = await client.post(url, json=payload, headers=headers)
                response.raise_for_status()
                issue = response.json()
                log.info(
                    f"GitHub issue created | repo={repo} | "
                    f"issue=#{issue['number']} | url={issue['html_url']}"
                )
                return {
                    "number":   issue["number"],
                    "url":      issue["html_url"],
                    "title":    issue["title"],
                    "repo":     repo,
                }
        except httpx.HTTPStatusError as e:
            log.error(f"GitHub API error {e.response.status_code}: {e.response.text}")
            return None
        except Exception as e:
            log.error(f"Failed to create GitHub issue: {e}")
            return None


# Global instance
vault = TokenVault()